server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:replication://10.128.11.46:3306/gfbusin?useUnicode=true&autoReconnect=true&useSSL=false&serverTimezone=Hongkong
    username: root
    password: zaq1@WSX
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    listener:
      simple:
        #手动ACK
        acknowledge-mode: manual
    publisher-confirms: true
    publisher-returns: true
  #        retry:
  #          enabled: true
  #          max-attempts: 5
  #          max-interval: 5000
  #          initial-interval: 5000
  #          multiplier: 2


  redis:
    host: 127.0.0.1
    port: 6379




