spring:
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
      #开启消息确认模式
    publisher-returns: true
    publisher-confirms: true
    template:
      #开启方法将消息返还给生产者
      mandatory: true
    listener:
      simple:
        #手动ACK
        acknowledge-mode: manual
        default-requeue-rejected: false
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
        retry:
          enabled: true

  datasource:
    url: jdbc:mysql:replication://127.0.0.1:3307
    username: root
    password: gdy430726

