server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:replication://10.128.11.46:3306/gfbusin
    username: root
    password: zaq1@WSX
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 消息确认（ACK）
    publisher-returns: true #确认消息已发送到队列(Queue)
    publisher-confirms: true #确认消息已发送到交换机(Exchange)


  redis:
    host: 127.0.0.1
    port: 6379
list:
  type: 1,2,3,4



